version: '3'
services:
  api-gateway:
    build: .
    container_name: api-gateway-container
    ports:
      - '8112:8765'
    command: bash -c "npm install && ./start-server.sh"
    volumes:
      - ./:/application
    env_file: .env
    # restart: always