version: '3'
services:
  bs_cms:
    image: apigateway:latest
    build:
         context: .
         dockerfile: Dockerfile
    environment:
      - DEPLOYMENT_TYPE=production
    volumes:
      - ./:/var/www/apigateway
    #  - .data:/data
    #  - ./docker/cms/logs:/var/log
    working_dir: /var/www/apigateway
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8025:8000"
    networks:
      - app-network
    stdin_open: true
    tty: true
#Docker Networks
networks:
  app-network:
    driver: bridge