rateLimit:
  enabled: true
  durationInSec: 5
  maxRequests: 1

services:
  - serviceName: Foundation
    path: foundation
    url: https://foundation-uatn.theblackswan.in
    rateLimitEnabled: false

  - serviceName: CMS
    path: cms
    url: https://cms-pre.theblackswan.in

  - serviceName: MASTER
    path: master
    url: https://master-service-uatn.theblackswan.in

  - serviceName: POSP
    path: posp
    url: https://posp-dev.zopperinsurance.com

