services:
  - serviceName: Foundation
    path: foundation
    url: https://foundation-uatn.theblackswan.in
    rateLimit:
      enabled: true
      maxRequests: 100
      windowMs: 60000

  - serviceName: CMS
    path: cms
    url: https://cms-pre.theblackswan.in
    rateLimit:
      enabled: true
      maxRequests: 100
      windowMs: 60000

  - serviceName: MASTER
    path: master
    url: https://master-service-uatn.theblackswan.in


  - serviceName: POSP
    path: posp
    url: https://posp-dev.zopperinsurance.com

